# This is a TOML document. Boom.

version = "1.0.0"
user = "nobody"
pid = "/tmp/{{.Name}}-service.pid"
dir = "./"
family = "go-saga-{{.Name}}"
env = "dev"

[log]
    dir = "/data/log/go-saga-{{.Name}}/"

# http://host:16686/search
[tracer]
    family = "saga-service"
    proto = "unixgram"
    addr = "/var/run/dapper-collect/dapper-collect.sock"

[bm]
    addr = "0.0.0.0:8000"
    maxListen = 10000
    timeout = "1000s"

[httpClient]
    dial = "2s"
    timeout = "10s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.breaker]
        window  = "10s"
        sleep   = "2000ms"
        bucket  = 10
        ratio   = 0.5
        request = 100

[orm]
    dsn = "root:root@tcp(0.0.0.0:3306)/angle_home?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"

[db]
    dsn = "root:root@tcp(0.0.0.0:3306)/angle_sms?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"

[redis]
    active = 100
    idle = 100
    idleTimeout = "3s"
    waitTimeout = "3s"
    wait = false
    name = "redis"
    proto = "tcp"
    addr = "127.0.0.1:6379"
    auth = "redis@123"
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"

[memcache]
    mcRecordExpire = "720h"
    [memcache.mc]
        name = "saga-admin"
        proto = "tcp"
        addr = "0.0.0.0:11211"
        idle = 5
        active = 10
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "10s"

[mail]
    host = "smtp.exmail.qq.com"
    port = 465
    from = "demo1@gmail.com"
    password = "pwd"
    to = ["demo1@gmail.com"]

[permit]
    [permit.Memcache]
        name = "go-business/auth"
        proto = "tcp"
        addr = "0.0.0.0:11232"
        active = 10
        idle = 10
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "80s"

[elastic]
host = "http://127.0.0.1:8080"
[elastic.HTTPClient]
    dial = "1s"
    timeout = "3s"
    keepAlive = "60s"
    timer = 1000
    [elastic.HTTPClient.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[property]
	[property.defaultproject]
        projectIDs=[682,4928,5822]
        status = ["created","pending","running","failed","success","canceled","skipped","manual"]
        types = [1]
        commitmrtypes = [0,1]
